### ISSUE TITLE
When the worker runs complete, the result  dont show

### ISSUE THREAD

**Issue by sanbei011** [langgenius/webapp-text-generator#26]
As shown in the `video` below, when the workflow is complete, the `run` has stopped transmitting, however, the results are `not` displayed, but always show `“Running”`.

[录屏 2024-07-25 10-11-37.webm](https://github.com/user-attachments/assets/b3b88d23-543e-418d-a55c-14ad2d9435b0)

**Comment by iamjoel** [comment]
Can't reproduced. Can you provide more info? @sanbei011

**Comment by sonicviz** [comment]
Is this the same issue
![image](https://github.com/user-attachments/assets/a4b494dc-ba43-478e-91c4-6493c0014aca)

I noticed two Tavily iterations didn't complete, and it was a consistent error. Doesn't happen with the web or preview versions, only using the template. Additionally it was only supposed to do 3 Tavily searches, but fired off 4 in the template with the last two hanging as shown.

**Comment by sanbei011** [comment]
Thank you very much, this problem has been fixed! Thank you for your efforts

**Comment by sonicviz** [comment]
Awesome, thanks!
