### ISSUE TITLE
Is it safe to use NEXT_PUBLIC_APP_KEY for storing an API key?

### ISSUE THREAD

**Issue by savokiss** [langgenius/webapp-text-generator#4]
As far as I know, the `NEXT_PUBLIC_` prefix is typically used for non-sensitive environment variables.

If you use this prefix to store an API key, there is a chance that it could be leaked, right?

**Comment by crazywoola** [comment]
See this [doc](https://vercel.com/docs/deployments/environments#managing-variables)

> When you define [Environment Variables](https://vercel.com/docs/projects/environment-variables) as key-value pairs using the dashboard or Vercel CLI, they are configured outside your source code. These variables are available to your source code during the build process.

I don't think the prefix will affect the security. It's more like a convention.
