### ISSUE TITLE
firefox 低版本52.0.2(32位)无法打开页面

### ISSUE THREAD

**Issue by EasonFeng5870** [langgenius/webapp-text-generator#8]
firefox版本：52.0.2 32位 2017.3月份版本
它会使用polyfills-xxxxx.js文件，是不是不支持HTML5的fetch特性呢？

现象就是，页面一直在loading等待，无法显示main页面内容。

**Comment by iamjoel** [comment]
Please use Chrome. We have't tested it in Firefox.
